services:
  db:
    image: mysql:8.3                          # official image
    container_name: university-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Berlin
    ports:
      - "3306:3306"                           # host → container
    volumes:
      - db-data:/var/lib/mysql               # persistent storage
      - ./db:/docker-entrypoint-initdb.d:ro  # bootstrap scripts
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
